name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Clear previous build
      run: |
        rm -rf Angular/final-project/dist/* || true
        rm -rf Server/dist/* || true

    - name: Install Angular dependencies
      working-directory: ./Angular/final-project
      run: npm ci

    - name: Build Angular app
      working-directory: ./Angular/final-project
      run: npm run build --prod

    - name: Install Server dependencies
      working-directory: ./Server
      run: npm ci

    - name: Build Docker image
      run: docker build -t my-app:latest .
